sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

before_script: 
  - greenkeeper-lockfile-update
  - sudo mount --make-shared /
  - sudo service docker stop
  - sudo sed -i 's/DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry 172.30.0.0\/16 /' /etc/default/docker
  - sudo service docker start
  - wget https://github.com/openshift/origin/releases/download/v3.7.0-alpha.1/openshift-origin-client-tools-v3.7.0-alpha.1-fdbd3dc-linux-64bit.tar.gz
  - tar xvzOf openshift-origin-client-tools-v3.7.0-alpha.1-fdbd3dc-linux-64bit.tar.gz > oc.bin
  - sudo mv oc.bin /usr/bin/oc
  - sudo chmod 755 /usr/bin/oc

script:
  - oc cluster up
  - sleep 10
  - npm run ci
# Only the node version 8 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
notifications:
  irc: "irc.freenode.org#bucharest-gold"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
